version: '2.4'
services:
    rsu1:
        hostname: rsu1
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  16384
    rsu2:
        hostname: rsu2
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:      
            kernel.msgmax:  16384
    obu1:
        hostname: obu1
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
        sysctls:      
            kernel.msgmax:  16384
    obu2:
        hostname: obu2
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40
        sysctls:      
            kernel.msgmax:  16384
    obu3:
        hostname: obu3
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50
        sysctls:      
            kernel.msgmax:  16384
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0

